### ISSUE TITLE
Doesn't compile!

### ISSUE THREAD

**Issue by extirpare** [kamgam/UnityEditorGitTool#1]
Compiler doesn't know what either of these 2 functions are:

EditorTools.ExecAndReadFirstLine("git rev-parse --short HEAD");
EditorTools.Exec("git status --porcelain");

**Comment by kamgam** [comment]
Thanks, my bad. Forgot to add the EditorTools class to the repo. I have now integrated these directly into the GitTools.cs in order to keep it all in one file. Please let me know if you have any other issues or reopen if the last commit did not resolve it (it should).
