### ISSUE TITLE
Settings keep being overwritten

### ISSUE THREAD

**Issue by ReneB** [kamgam/UnityEditorGitTool#4]
Hello! Let me start off by saying "thanks" for creating this tool and sharing it with the community - it really helped us a lot to not have to figure out the interfacing with Git by ourselves.

However, it might just be me, but in my install, my settings for this plugin kept being overwritten. I tracked this to the code in `GitToolSettings.GetOrCreateSettings()` always failing to load the `GitToolSettings` ScriptableObject from the given path.

I _think_ the issue is that Unity is very particular about the way things like MonoBehavior and ScriptableObject classes are supposed to behave - I think loading ScriptableObjects _only_ works _if there is a file that declares the class with the exact name of the class_.

But in this plugin, the `GitToolSettings` class is in the main file - `EditorGitTools.cs` - which prevents it from loading properly - to which the code responds by creating a new asset at that path, effectively overwriting the old one.

I fixed this locally by moving the `GitToolSettings` class into its own file, but since I had to put the plugin in my own project, I also made some other changes to code style and removing the backward compatibility for Unity 2017 and before, so that one is not directly suitable for a PR. However, if you'd like a PR, I'm fully willing to create one for you.

**Comment by kamgam** [comment]
Hi, sorry for replying so late. I must have missed the message from GitHub. It has been fixed in the latest version (it's now two files). Thank you for reporting this.
